### ISSUE TITLE
metadata.rb version for 0.5.0

### ISSUE THREAD

**Issue by pdunnavant** [hectcastro/chef-collectd#31]
I see you have a tag for this repo here: https://github.com/hectcastro/chef-collectd/tree/v0.5.0

However, the metadata.rb version still says 0.4.4. Was that intentional, or should it be updated to 0.5.0?

Thanks!

**Comment by hectcastro** [comment]
You are correct, I missed this in the version bumping process. Thanks, @pdunnavant.

Fixed in https://github.com/hectcastro/chef-collectd/commit/34b37f54c14df7275ebad9debd9302d89ec30c34.

**Comment by pdunnavant** [comment]
Thanks for getting this resolved so quickly! And thanks for this cookbook as well. It's been very helpful!
