### ISSUE TITLE
Push 1.2.1 to Supermarket?

### ISSUE THREAD

**Issue by pdunnavant** [hectcastro/chef-collectd#53]
Would you mind pushing the latest 1.2.1 version to Supermarket?

Also, I just found out that this cookbook was the same as collectd-ng in Supermarket:
https://supermarket.chef.io/cookbooks/collectd-ng

Would it make sense at all to rename this cookbook in `metadata.rb` to be `collectd-ng` as well? I likely would have found it faster in Supermarket if that were the case. :-)

Thanks!

**Comment by hectcastro** [comment]
There was a push for this in https://github.com/hectcastro/chef-collectd/issues/45, but no one really chimed in to confirm that everything was working well (I test changes using Test Kitchen, but I don't actually use this cookbook in a production environment).

If you're willing to test it, I just rebased the [`feature/hmc/chef-supermarket`](https://github.com/hectcastro/chef-collectd/tree/feature/hmc/chef-supermarket) with `develop`.

**Comment by pdunnavant** [comment]
Sure thing! I'll test that tomorrow for you.

**Comment by pdunnavant** [comment]
@hectcastro Yup! It looks good! Sorry for the delay, got busy with other things yesterday and just got to try it out. Thanks!
