### ISSUE TITLE
Release v1.2.1 on Chef Supermarket

### ISSUE THREAD

**Issue by sgerrand** [hectcastro/chef-collectd#60]
I noticed that version 1.2.0 of this cookbook [is available on the Chef Supermarket](https://supermarket.chef.io/cookbooks/collectd-ng/versions/1.2.0), but version 1.2.1 (which has a significant bug fix for the previous version) [isn't](https://supermarket.chef.io/cookbooks/collectd-ng/versions/1.2.1).

Will version 1.2.1 be released on the Chef Supermarket?

**Comment by hectcastro** [comment]
See: https://supermarket.chef.io/cookbooks/collectd-ng/versions/1.2.1
